name: output
on: push
jobs:
  build:
    outputs:
      version: ${{ steps.step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step1
        run:  echo "version=0.1" >> $GITHUB_OUTPUT
      - name: step2
        run:  echo "the version ${{ steps.step1.outputs.version }}"
  delopy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: second
        run: echo "depoy ${{needs.build.outputs.version}}"
