name: git
on: push
env:
  APP_ENV: "dev"
jobs:
  job-1:
    env:
      APP_ENV: "test"
    runs-on: ubuntu-22.04
    steps:
      - name: 1st
        env:
          APP_ENV: "prod"
        run: echo "1st $APP_ENV"
