name: test-input
on: push
jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: using variables
        run: |
          echo "workflow ${{github.actor}}"
          echo "rep ${{github.repository}}"
          echo "${{github.ref_name}}"
      - name: print all variables
        run :  echo"${{toJson(github)}}"
